package org.openflux.app.data

enum class SshAuthMethod { PASSWORD, KEY }
enum class TlsMode { DOMAIN, IP }
enum class DeployStatus { NONE, RUNNING, SUCCESS, FAILED }

/**
 * A server as the rest of the app sees it: [DeployServerEntity]'s non-secret
 * fields joined with the secret material [DeployServerSecretsStore] holds
 * for the same id - same split as [Profile]/[ProfileEntity]/[SecretsStore].
 *
 * Mirrors exactly what deploy/install.sh asks for (see its ask/ask_secret
 * calls), plus the SSH connection details needed to reach it in the first
 * place.
 */
data class DeployServer(
    val id: String = "",
    val name: String = "",
    val host: String = "",
    val port: Int = 22,
    val username: String = "root",
    val authMethod: SshAuthMethod = SshAuthMethod.PASSWORD,
    val sshPassword: String = "",
    val sshPrivateKeyPem: String = "",
    val sshPassphrase: String = "",
    val tlsMode: TlsMode = TlsMode.DOMAIN,
    val domain: String = "",
    val email: String = "",
    val repoUrl: String = "https://github.com/wlruscfd/openflux-server.git",
    val gitRef: String = "main",
    val deployScriptUrl: String = "https://raw.githubusercontent.com/wlruscfd/openflux-deploy/main/install.sh",
    val registerNode: Boolean = true,
    val nodeName: String = "node-1",
    val nodeMaxKeys: Int = 500,
    // Generated by the app itself (see DeployServerRepository.save) rather
    // than left for install.sh to invent, so they're known - and usable for
    // key management via ControlPlaneAdminClient - the moment this server
    // is saved, before any deploy has even run.
    val adminToken: String = "",
    val dbPassword: String = "",
    val knownHostKeyFingerprint: String = "",
    val lastDeployStatus: DeployStatus = DeployStatus.NONE,
    val lastDeployAt: Long = 0,
) {
    /** Where this server's controlplane (once deployed) is reachable. */
    val baseUrl: String get() = "https://" + if (tlsMode == TlsMode.DOMAIN) domain else host
}
